#!/bin/bash
#SBATCH --job-name=threaded_job_MaxwellMPI	#OPENMP Jobname
#SBATCH --mail-type=END,FAIL			# Mail event(none,begin,end,fail,all)
#SBATCH --mail-user=iab533@york.ac.uk	# Where to send email
#SBATCH --ntasks=16				        #Run on a single CPU
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=1			    #...with 8 cores
#SBATCH --time=00:10:00				    # Time limit hrs:min:sec
#SBATCH --output=MaxwellMPI_%j.log	# Standard Output and error log
#SBATCH --partition=teach			    # run in the teaching queue
#SBATCH --mem-per-cpu=2gb
#SBATCH --exclusive

echo Working directory is `pwd`
echo Running job on host
echo -e '\t' `hostname` at `date`
echo $SLURM_CPUS_ON_NODE CPU cores available
echo $SLURM_JOB_NODELIST - job number
echo

module load compiler/GCC/10.2.0
module load mpi/OpenMPI/4.0.5-GCC-10.2.0

mpiexec -n ${SLURM_NTASKS} "/users/iab533/scratch/HIPC-Assignment/maxwell - MPI/maxwell"

printf "\n\nOn a 100 x 100 grid\n\n"
mpiexec -n ${SLURM_NTASKS} "/users/iab533/scratch/HIPC-Assignment/maxwell - MPI/maxwell -x 100 -y 100 -f 1 -o mpi/my_sim -n 1000"
printf "\n\nOn a 400 x 400 grid\n\n"
mpiexec -n ${SLURM_NTASKS} "/users/iab533/scratch/HIPC-Assignment/maxwell - MPI/maxwell -x 400 -y 400 -f 1 -o mpi/my_sim -n 1000"
printf "\n\nOn a 1000 x 1000 grid\n\n"
mpiexec -n ${SLURM_NTASKS} "/users/iab533/scratch/HIPC-Assignment/maxwell - MPI/maxwell -x 1000 -y 1000 -f 1 -o mpi/my_sim -n 1000"
printf "\n\nOn a 2000 x 2000 grid\n\n"
mpiexec -n ${SLURM_NTASKS} "/users/iab533/scratch/HIPC-Assignment/maxwell - MPI/maxwell -x 2000 -y 2000 -f 1 -o mpi/my_sim -n 1000"

echo 
echo Job finished at `date`


